### ISSUE TITLE
¿Como manejar las dimensiones del paquete?

### ISSUE THREAD

**Issue by Puerco-Potter** [gento-arg/magento-oca#2]
Hola, logre instalar tú modulo con relativa facilidad en Magento 2.3.2 y estoy muy agradecido que lo compartas.
Vi que tenés opciones para el volumen mínimo de paquete en la configuración del método de envío.
Pero me surge la duda de como manejas las dimensiones fuera de eso.
¿Tendría que crear un atributo "volume"?
¿O lo estás calculando en base ts_dimensions?
¿Cómo manejas múltiples productos?
Te pregunto porque el paquete estandarizado que nos entregó OCA es de 0.008 m3 y somos una tienda de ropa, es decir que en un solo paquete entran varias remeras por ejemplo pero solo un paquete de zapatillas, entonces me gustaría tener claro como se hacen los cálculos del bulto y que datos tendria que cargar en mis productos.
Desde ya muchas gracias.

**Comment by manuelcanepa** [comment]
TLDR; No.

Actualmente el desarrollo se penso para una empresa de indumentaria deportiva y no hubo demanda al respecto de volumen porque los bultos que manejan son casi siempre similares. De todas formas, lo dejo como una mejora para poder desarrollarlo.

**Comment by manuelcanepa** [comment]
@Puerco-Potter  Se agregó el release 1.0.5 el feature
